# aliases
alias gst='git status'
alias grea='git pull'
alias gwr='git commit -am'
alias co='git checkout'
alias newbr='git checkout -b'
alias graph='git log --oneline --graph --abbrev-commit --pretty=format:"%Cgreen %h %Creset%s %n%an - %cr %n%n"'
alias reb='git rebase'
alias lcd='cd c:/localdev/'
alias rebc='git rebase --continue'
alias ngxS='sudo nginx'
alias ngxK='sudo nginx -s stop'
alias ngxR='sudo nginx -s reload'
alias wcslog='tail -f -n 1000 /Applications/Oracle/WebCenter/Sites/11gR1/Sites/11.1.1.8.0/logs/sites.log'
alias copy="tr -d '\n' | pbcopy"
